### ISSUE TITLE
`admin` should not be a role

### ISSUE THREAD

**Issue by moveson** [moveson/edify#93]
Having `admin` as a role is dangerous and results in the kind of complexity demonstrated by needing to have `ASSIGNABLE_ROLES`.

We should add an `admin` boolean back to the `users` table.

- [x] Migration to add `admin` boolean column (#94)
- [x] Set `admin` attribute on existing users (#94)
- [x] Point admin-based logic at the boolean field (#95)
- [x] Delete `admin` as an enum option from the User model (#94)
- [x] Simplify "assignable roles" logic (#95)
